# Generated by Django 4.2.6 on 2023-11-07 04:32

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.ImageField(max_length=254, upload_to='image/', validators=[catalog.models.Application.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
